apiVersion: v1
kind: DeploymentConfig
metadata:
  name: acct-mgt
  labels:
    app: acct-mgt 
spec:
  replicas: 1
  selector:
    app: acct-mgt
    deploymentconfig: acct-mgt
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: acct-mgt
        deploymentconfig: acct-mgt
    spec:
      serviceAccountName: acct-mgt-sa
      automountServiceAccountToken: True
      containers:
      - image: docker.io/robertbartlettbaron/acct-mgt.ppc64le:latest
        imagePullPolicy: Always
        name: acct-mgt
        resources:
          limits:
            memory: 1024Mi
            cpu: 2000m
          requests:
            memory: 150Mi
            cpu: 250m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  test: False
  triggers:
  - type: ConfigChange

