apiVersion: v1
kind: DeploymentConfig
metadata:
  name: acct-req
  labels:
    app: acct-req 
spec:
  replicas: 1
  selector:
    app: acct-req
    deploymentconfig: acct-req
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: acct-req
        deploymentconfig: acct-req
    spec:
      serviceAccountName: acct-req-sa
      automountServiceAccountToken: True
      containers:
      - image: docker.io/robertbartlettbaron/rbb_utility:latest
        # image: docker.io/mirrorgooglecontainers/acct-req:latest
        imagePullPolicy: Always
        name: acct-req
        resources:
          limits:
            memory: 1024Mi
            cpu: 2000m
          requests:
            memory: 150Mi
            cpu: 250m
        #terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  test: False
  triggers:
  - type: ConfigChange

