apiVersion: v1
kind: ClusterResourceQuota
metadata:
  name: cluster-resource-quota
spec:
  quota: 
    hard:
      pods: "10"
      secrets: "20"
  selector:
    annotations: 
      openshift.io/requester: skanthed@redhat.com
    labels: 
      matchLabels:
        name: su
  status:
  namespaces: 
    namespace: acct-mgt
    status:
      hard:
        pods: "10"
        secrets: "20"
      used:
        pods: "1"
        secrets: "9"
  total: 
    hard:
      pods: "10"
      secrets: "20"
    used:
      pods: "1"
      secrets: "9"
