apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onboarding

resources:
  - ../../base

secretGenerator:
  - name: onboarding-credentials
    envs:
      - credentials.env

configMapGenerator:
  - name: onboarding-config
    envs:
      - config.env
