secretGenerator:
- name: basic-auth
  namespace: onboarding
  behavior: create
  literals:
  - username=admin
  - password=pass
bases:
  - ../../base
resources:
  - patches/route.yaml
patchesStrategicMerge:
  - patches/deployment.yaml
  - patches/image-stream.yaml
