secretGenerator:
- name: basic-auth
  namespace: onboarding
  behavior: create  
  literals:
  - admin=pass
bases:
  - ../../base
patchesStrategicMerge:
  - patches/route.yaml
  - patches/deployment-config.yaml
  - patches/image-stream.yaml
