apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  namespace: onboarding
spec:
  template:
    spec:
      containers:
      - name: onboarding
        env:
          - name: OPENSHIFT_URL
            value: "api.crc.testing:6443"
          - name: OPENSHIFT_VERSION
            value: "4"
          - name: ACCT_MGT_IDENTITY_PROVIDER
            value: "Developer"
          - name: ACCT_MGT_QUOTA_DEF_FILE
            value: /app/quota/quota
          - name: ACCT_MGT_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: username
          - name: ACCT_MGT_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: password
        image: "docker.io/robertbartlettbaron/acct-mgt.x86:latest"
