apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: onboarding
        env:
          - name: OPENSHIFT_VERSION
            value: "4"
          - name: OPENSHIFT_URL
            value: https://kubernetes.default.svc
          - name: ACCT_MGT_QUOTA_DEF_FILE
            value: /app/config/quotas.json
          - name: ACCT_MGT_LIMIT_DEF_FILE
            value: /app/config/limits.json
        envFrom:
          - secretRef:
              name: onboarding-credentials
          - configMapRef:
              name: onboarding-config
        image: "localhost:5000/cci-moc/openshift-acct-mgt:latest"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: config-vol
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: config-vol
          configMap:
            name: config-files
      serviceAccountName: onboarding-serviceaccount
      automountServiceAccountToken: true
