apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: onboarding
        env:
          - name: OPENSHIFT_VERSION
            value: "4"
          - name: OPENSHIFT_URL
            value: https://kubernetes.default.svc
          - name: ACCT_MGT_QUOTA_DEF_FILE
            value: /app/quota/quotas.json
        envFrom:
          - secretRef:
              name: onboarding-credentials
          - configMapRef:
              name: onboarding-config
        image: openshift-acct-mgt:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: quota-vol
            mountPath: /app/quota
            readOnly: true
      volumes:
        - name: quota-vol
          configMap:
            name: openshift-quota-definition
      serviceAccountName: onboarding-serviceaccount
      automountServiceAccountToken: true
