apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: onboarding
        env:
        - name: OPENSHIFT_URL
          value: KUSTOMIZE
        - name: OPENSHIFT_VERSION
          value: KUSTOMIZE
        - name: ACCT_MGT_IDENTITY_PROVIDER
          value: KUSTOMIZE
        image: KUSTOMIZE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: quota-vol
            mountPath: /app/quota
            readOnly: true
      serviceAccountName: onboarding-serviceaccount
      automountServiceAccountToken: True
      volumes:
        - name: quota-vol
          configMap: 
            name: openshift-quota-definition 
