apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onboarding

commonLabels:
  app: onboarding

resources:
- namespace.yaml
- cluster-role-binding.yaml
- deployment.yaml
- image-stream.yaml
- route.yaml
- service-account.yaml
- service.yaml

configMapGenerator:
  - name: config-files
    files:
      - limits.json
      - quotas.json
