commonLabels:
  app: onboarding
namespace: onboarding
resources:
- cluster-role-binding.yaml
- quotaConfigmap.yaml
- deployment.yaml
- image-stream.yaml
- route.yaml
- service-account.yaml
- service.yaml
