name: Functional tests
on:
  push:
  pull_request:

jobs:
  run-functional-tests:
    name: Run functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Microshift
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

          echo '127.0.0.1  onboarding-onboarding.cluster.local' | sudo tee -a /etc/hosts

          sudo docker run -d --rm --name microshift --privileged \
          --network host \
          -v microshift-data:/var/lib \
          quay.io/microshift/microshift-aio:latest

          sudo docker run -d --name registry --network host registry:2

          sleep 30

          curl -O https://mirror.openshift.com/pub/openshift-v4/$(uname -m)/clients/ocp/stable/openshift-client-linux.tar.gz
          sudo tar -xf openshift-client-linux.tar.gz -C /usr/local/bin oc kubectl

          mkdir ~/.kube
          sudo docker cp microshift:/var/lib/microshift/resources/kubeadmin/kubeconfig ~/.kube/config
          oc get all

          sudo docker build . -t "localhost:5000/cci-moc/openshift-acct-mgt:latest"
          sudo docker push "localhost:5000/cci-moc/openshift-acct-mgt:latest"

          oc apply -k k8s/overlays/crc
          oc wait -n onboarding --for=condition=available --timeout=800s deployment/onboarding

          sleep 90

          curl -u admin:pass https://onboarding-onboarding.cluster.local/users/test -k

          # Having issues with the route never working at first,
          # but recreating the container fixes it
          sudo docker stop microshift
          sudo docker run -d --rm --name microshift --privileged \
            --network host \
            -v microshift-data:/var/lib \
            quay.io/microshift/microshift-aio:latest

          sleep 30

          oc wait -n onboarding --for=condition=available --timeout=800s deployment/onboarding

          sleep 90

          curl -u admin:pass https://onboarding-onboarding.cluster.local/users/test -k

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run functional tests
        run: |
          pytest tests/functional -v --cov=acct_mgt --cov-report=term \
            --admin-user admin --admin-password pass \
            --api-endpoint https://onboarding-onboarding.cluster.local
