name: Functional tests
on:
  push:
  pull_request:

jobs:
  run-functional-tests:
    name: Run functional tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Microshift
        run: |
          ./ci/setup.sh

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run functional tests
        run: |
          ./ci/run_functional_tests.sh
