name: Unit tests
on:
  push:
  pull_request:

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit -v --cov=acct_mgt --cov-report=term
